name: debezium-platform
description: Debezium Platform
version: 0.0.1
apiVersion: v2
keywords:
  - debezium
  - cdc
sources:
  - https://github.com/debezium/debezium-platform-conductor
home: https://github.com/debezium/debezium-platform-conductor
dependencies:
    - name: debezium-operator
      #TODO update to 3.0.5-final
      version: "3.0.4-final"
      repository: "https://charts.debezium.io"
    - name: database
      version: 0.0.1
      condition: database.enabled
