domain:
  url: ""
stage:
  image: quay.io/debezium/platform-stage:latest
conductor:
  image: quay.io/debezium/platform-conductor:nightly
  offset:
    existingConfigMap: ""
offsets:
  reusePlatformDatabase: true
  database:
    enabled: false
    name: postgres
    host: postgres
    auth:
      existingSecret: ""
database:
  enabled: false
  name: postgres
  host: postgres
  auth:
    existingSecret: ""
env: []