name: Test Debezium platform (conductor)
on:
  push:
    paths:
      - "debezium-platform-conductor/**"
    branches:
      - main
  pull_request:
    paths:
      - "debezium-platform-conductor/**"
    branches:
      - main
jobs:
  build_cache:
    name: "Update Dependencies"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: debezium-platform-conductor
    outputs:
      cache_key: ${{ steps.set-cache-key.outputs.cache_key }}
    steps:
      - name: Checkout core repository
        uses: actions/checkout@v5
        with:
          repository: debezium/debezium
          ref: main
          path: debezium-platform-conductor/core
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set cache key
        id: set-cache-key
        run: echo "cache_key=${{ hashFiles('./debezium-platform-conductor/core/**/pom.xml') }}" >> "$GITHUB_OUTPUT"
      - id: maven-cache-check
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-debezium-platform-test-build-${{ steps.set-cache-key.outputs.cache_key }}
          restore-keys: maven-debezium-platform-test-build-${{ steps.set-cache-key.outputs.cache_key }}
      - name: Maven build core dependencies
        if: steps.maven-cache-check.outputs.cache-hit != 'true'
        run: >
          ./core/mvnw clean install -f core/pom.xml 
          -DskipTests 
          -DskipITs 
          -Dformat.formatter.goal=validate
          -Dformat.imports.goal=check 
          -Dhttp.keepAlive=false 
          -Dmaven.wagon.http.pool=false
          -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
          -Dmaven.javadoc.skip=true 
          -Dstyle.color=always 
          --no-transfer-progress
          -T4
      - name: Checkout operator repository
        uses: actions/checkout@v5
        with:
          repository: debezium/debezium-operator
          ref: main
          path: debezium-platform-conductor/operator
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set cache key
        id: set-operator-cache-key
        run: echo "cache_key=${{ hashFiles('./debezium-platform-conductor/operator/**/pom.xml') }}" >> "$GITHUB_OUTPUT"
      - id: maven-operator-cache-check
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-debezium-platform-test-build-${{ steps.set-operator-cache-key.outputs.cache_key }}
          restore-keys: maven-debezium-platform-test-build-${{ steps.set-operator-cache-key.outputs.cache_key }}
      - name: Maven build operator dependency
        if: steps.maven-operator-cache-check.outputs.cache-hit != 'true'
        run: >
          ./operator/mvnw clean install -f operator/pom.xml 
          -DskipTests 
          -DskipITs 
          -Dformat.formatter.goal=validate
          -Dformat.imports.goal=check 
          -Dhttp.keepAlive=false 
          -Dmaven.wagon.http.pool=false
          -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
          -Dmaven.javadoc.skip=true 
          -Dstyle.color=always 
          --no-transfer-progress
          -T4
  check_style:
    name: "Checkstyle and Formatting"
    needs: [ build_cache ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: debezium-platform-conductor
    steps:
      - name: Checkout Action
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Repository
        id: cache-check
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-debezium-platform-test-build-${{needs.build_cache.outputs.cache_key}}
          restore-keys: maven-debezium-platform-test-build-${{needs.build_cache.outputs.cache_key}}

      - name: "Checkstyle, Formatting, and Import Order Checks"
        run: >
          ./mvnw -B -ntp process-sources checkstyle:checkstyle
          -Dformat.formatter.goal=validate
          -Dformat.imports.goal=check
          -Dorg.slf4j.simpleLogger.showDateTime=true
          -Dorg.slf4j.simpleLogger.dateTimeFormat="YYYY-MM-dd HH:mm:ss,SSS"
  tests:
    name: "Run tests"
    needs: [ check_style]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: debezium-platform-conductor
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Repository
        id: cache-check
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-debezium-platform-test-build-${{needs.build_cache.outputs.cache_key}}
          restore-keys: maven-debezium-platform-test-build-${{needs.build_cache.outputs.cache_key}}
      
      - name: Run tests
        run: ./mvnw clean verify