name: Test Debezium platform (conductor)
on:
  push:
    paths:
      - "debezium-platform-conductor/**"
    branches:
      - main
  pull_request:
    paths:
      - "debezium-platform-conductor/**"
    branches:
      - main
jobs:
  check_style:
    name: "Checkstyle and Formatting"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: debezium-platform-conductor
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Repository
        id: cache-check
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-debezium-platform-test-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-debezium-platform-test-build-${{ hashFiles('**/pom.xml') }}

      - name: "Checkstyle, Formatting, and Import Order Checks"
        run: >
          ./mvnw -B -ntp process-sources checkstyle:checkstyle
          -Dformat.formatter.goal=validate
          -Dformat.imports.goal=check
          -Dorg.slf4j.simpleLogger.showDateTime=true
          -Dorg.slf4j.simpleLogger.dateTimeFormat="YYYY-MM-dd HH:mm:ss,SSS"
  tests:
    name: "Run tests"
    needs: [ check_style]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: debezium-platform-conductor
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Repository
        id: cache-check
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-debezium-platform-test-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-debezium-platform-test-build-${{ hashFiles('**/pom.xml') }}
      
      - name: Run tests
        run: ./mvnw clean verify