name: Test Debezium platform (stage)
on:
  push:
    paths:
      - "debezium-platform-stage/**"
    branches:
      - main
  pull_request:
    paths:
      - "debezium-platform-stage/**"
    branches:
      - main
jobs:
  type-check:
    name: "TypeScript Type and Lint Check"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: debezium-platform-stage
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn/cache
            debezium-platform-stage/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('debezium-platform-stage/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint check
        run: yarn lint

      - name: Run TS Type Check
        run: yarn type-check

  tests:
    name: "Build the project & Run tests"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: debezium-platform-stage
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn/cache
            debezium-platform-stage/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('debezium-platform-stage/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build UI
        run: yarn build
      
      - name: Run tests
        run: yarn test